export const videos = [
  {
    id: 324393,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 1212121,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 55555,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 11111,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 3243931,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 12121211,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 555551,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 111111,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 3243934,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 12121215,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 555556,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
  {
    id: 1111178,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'Nicolas',
      email: 'nico@las.com',
    },
  },
];
